CREATE TABLE IF NOT EXISTS `CUSTOMER`(
    CUSTOMER_ID int AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL UNIQUE,
    PHONE int NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(300),
    PINCODE BIGINT,
    LOCALITY VARCHAR(50),
    CITY VARCHAR(50),
    STATE VARCHAR(50),
    ADDRESS_TYPE VARCHAR(10)

)ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;