CREATE TABLE IF NOT EXISTS `ORDERS`(
    ORDER_ID VARCHAR(100) NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    PRODUCT_PURCHASED VARCHAR(300) NOT NULL,
    PRODUCT_PRICE INT NOT NULL,
    PAYMENT_MODE VARCHAR(50) NOT NULL,
    CUSTOMER_NAME VARCHAR(300) NOT NULL,
    PURCHASE_DATE DATE NOT NULL,
    PURCHASE_TIME TIME NOT NULL,
    PRODUCT_IMAGE VARCHAR(200) NOT NULL,
    FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;