CREATE TABLE IF NOT EXISTS `PRODUCT_REVIEW`(
 SNo INT PRIMARY KEY AUTO_INCREMENT,
 CUSTOMER_NAME VARCHAR(100) NOT NULL,
 PRODUCT_ID INT NOT NULL,
 RATING INT NOT NULL,
 REVIEW VARCHAR(200) NOT NULL

)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;